### ISSUE TITLE
1.0.6 does not move the tooltip

### ISSUE THREAD

**Issue by mohcow** [Repooc/ElvUI_ToolTipTweaks#1]
basically the title, 1.0.6 does not move the tooltip at all. reverting back to 1.0.5 and it works again.

**Comment by Repooc** [comment]
Not showing anything doesn't help as there are multiple settings and have to reset them up as the tooltip options have changed

**Comment by Repooc** [comment]
crap i did find a typo
will push another release which hopefully fixes what u found, assuming ur issue is after u moved the mover which i didnt test as thoroughly as if u reset or dont move the tooltip mover

**Comment by Repooc** [comment]
try 1.07 should fix the typo as i moved db stuff and forgot to update it for the mover moved part for some of it

**Comment by mohcow** [comment]
looking good. thank you!
